services:
  - type: web
    name: routine-tracker
    runtime: ruby
    plan: free

    buildCommand: |
      bundle install

    startCommand: |
      bundle exec rails db:prepare
      bundle exec rails server -b 0.0.0.0 -p $PORT

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: routine-tracker-db
          property: connectionString

      - key: RAILS_ENV
        value: production

databases:
  - name: routine-tracker-db
    plan: free